public abstract class Emoji {
    public static String CHECKERED_FLAG = "\uD83C\uDFC1"; //🏁
    public static String DUCK = "\uD83E\uDD86"; //🦆
    public static String ARROW_RIGHT = "➡"; //➡
    public static String ARROW_LEFT = "⬅"; //⬅
    public static String ARROW_UP = "⬆"; //⬆
    public static String ARROW_DOWN = "⬇"; //⬇
    public static String HOLE = "\uD83D\uDD73"; //🕳
    public static String HOUSE = "\uD83C\uDFE0"; //🏠
    public static String BRIDGE = "\uD83C\uDF09"; //🌉
    public static String CACTUS = "\uD83C\uDF35"; //🌵
    public static String CASTLE = "\uD83C\uDFF0"; //🏰
    public static String SKULL = "\uD83D\uDC80"; //💀
    public static String BIRD = "\uD83D\uDC26"; //🐦
    public static String TREE = "\uD83C\uDF33"; //🌳
    public static String EVERGREEN_TREE = "\uD83C\uDF32"; //🌲
    public static String FIRE = "\uD83D\uDD25"; //🔥
    public static String DROPLET = "\uD83D\uDCA7"; //💧
    public static String RAINBOW = "\uD83C\uDF08"; //🌈
    public static String LIGHTNING = "⚡"; //⚡
    public static String SPARKLES = "✨"; //✨
    public static String STAR = "⭐"; //⭐
    public static String PAWN = "♟"; //♟
    public static String DICE = "\uD83C\uDFB2"; //🎲
    public static String GHOST = "\uD83D\uDC7B"; //👻
    public static String FOG = "\uD83C\uDF01"; //🌁
    public static String BEER = "\uD83C\uDF7A"; //🍺
    public static String SIREN = "\uD83D\uDEA8"; //🚨
    public static String SKULL_AND_CROSSBONES_2 = "☠"; //☠
    public static String HATCHING_EGG = "\uD83D\uDC23"; //🐣
    public static String HURT = "\uD83E\uDD15"; //🤕
    public static String ROBOT = "\uD83E\uDD16"; //🤖
    public static String GUN = "\uD83D\uDD2B"; //🔫
    public static String CROSSED_SWORDS = "⚔"; //⚔
    public static String SHIELD = "\uD83D\uDEE1"; //🛡
    public static String DOOR = "\uD83D\uDEAA"; //🚪
    public static String PENGUIN = "\uD83D\uDC27"; //🐧
    public static String EAGLE = "\uD83E\uDD85"; //🦅
    public static String OWL = "\uD83E\uDD89"; //🦉
    public static String DRAGON = "\uD83D\uDC09"; //🐉
    public static String DRAGON_FACE = "\uD83D\uDC32"; //🐲
    public static String TURKEY = "🦃"; //🦃
    public static String ROOSTER = "\uD83D\uDC13"; //🐓
    public static String CHICKEN = "\uD83D\uDC14"; //🐔
    public static String TURTLE = "\uD83D\uDC22"; //🐢
    public static String BEE = "\uD83D\uDC1D"; //🐝
    public static String BOMB = "\uD83D\uDCA3"; //💣
    public static String BOW = "\uD83C\uDFF9"; //🏹
    public static String BAT = "\uD83E\uDD87"; //🦇
    public static String SPIDER = "\uD83D\uDD77"; //🕷
    public static String SNAKE = "\uD83D\uDC0D"; //🐍
    public static String KNIFE = "\uD83D\uDD2A"; //🔪
    public static String CIRCLE = "⚫"; //⚫
    public static String AMOGUS = "ඞ"; //ඞ
    public static String HALO = "\uD83D\uDE07"; //😇
    public static String SMILEY = "\uD83D\uDE00"; //😀
    public static String THINK = "\uD83E\uDD14"; //🤔
    public static String SQUARE = "⬛"; //⬛
    public static String EXPLOSION = "\uD83D\uDCA5"; //💥
    public static String X = "\uD83D\uDDD9"; //🗙
    public static String TURN_LEFT = "↩"; //↩
    public static String CHECKMARK = "✔"; //✔

    public static String BOAT = "⛴"; //⛴
    public static String SPEEDBOAT = "\uD83D\uDEA4"; //🚤
    public static String HUGE_BOAT = "\uD83D\uDEF3"; //🛳
    public static String SMALL_BOAT = "\uD83D\uDEA2"; //🚢
    public static String SUBMARINE = "\uD83D\uDE85"; //🚅

    public static String SQUID = "\uD83E\uDD91"; //🦑
    public static String SHARK = "\uD83E\uDD88"; //🦈
    public static String WHALE = "\uD83D\uDC0B"; //🐋
    public static String CRAB = "\uD83E\uDD80"; //🦀
    public static String VORTEX = "\uD83C\uDF00"; //🌀 //🛸

    public static String ROWBOAT = "\uD83D\uDEA3"; //🚣
    public static String SAILBOAT = "⛵"; //⛵
    public static String SKULL_AND_CROSSBONES = "\uD83D\uDD71"; //🕱
    public static String CANOE = "\uD83D\uDEF6"; //🛶

    public static String SHOOTING_STAR = "\uD83C\uDF20"; //🌠
    public static String GALAXY = "\uD83C\uDF0C"; //🌌
    public static String ROCKET = "\uD83D\uDE80"; //🚀
    public static String ALIEN_MONSTER = "\uD83D\uDC7E"; //👾
    public static String ALIEN = "\uD83D\uDC7D"; //👽
    public static String SATELLITE_ANTENNA = "\uD83D\uDCE1"; //📡
    public static String RADIOACTIVE = "☢"; //☢
    public static String SATELLITE = "\uD83D\uDEF0"; //🛰;
    public static String DRUM = "\uD83E\uDD41"; //🥁

}
